server:
  port: 8080
sso:
  saml:
    idp-xml: idp-okta.xml
    publicKeyCert: localhost.cert
    privateKeyCert: localhost.key.der
    entityBaseURL: http://localhost:8080
    entityId: urn:test:linxl:guangzhou:keyou